export const recentPayments = [
  {
    transactionId: 1,
    clientName: 'Bink MacPhail',
    date: '2/14/2023',
    status: false,
    amount: '$3.49',
    service: 'Push',
  },
  {
    transactionId: 2,
    clientName: 'Bay Ridler',
    date: '12/6/2022',
    status: false,
    amount: '$6.44',
    service: 'Push',
  },
  {
    transactionId: 3,
    clientName: 'Scarlett Wyche',
    date: '10/31/2022',
    status: true,
    amount: '$6.75',
    service: 'Push',
  },
  {
    transactionId: 4,
    clientName: 'Birk Coolahan',
    date: '7/6/2023',
    status: true,
    amount: '$6.43',
    service: 'Push',
  },
  {
    transactionId: 5,
    clientName: 'Farra Coatts',
    date: '3/8/2023',
    status: false,
    amount: '$5.51',
    service: 'Push',
  },
  {
    transactionId: 6,
    clientName: 'Jobey Patemore',
    date: '9/9/2022',
    status: true,
    amount: '$7.69',
    service: 'Push',
  },
  {
    transactionId: 7,
    clientName: 'Stu Bullough',
    date: '1/3/2023',
    status: true,
    amount: '$5.43',
    service: 'Push',
  },
  {
    transactionId: 8,
    clientName: 'Krystle Cushelly',
    date: '7/28/2022',
    status: false,
    amount: '$0.14',
    service: 'Push',
  },
  {
    transactionId: 9,
    clientName: 'Laurent Ondrus',
    date: '10/9/2022',
    status: true,
    amount: '$1.12',
    service: 'Push',
  },
  {
    transactionId: 10,
    clientName: 'Jimmy Oyley',
    date: '12/20/2022',
    status: true,
    amount: '$4.58',
    service: 'Push',
  },
  {
    transactionId: 11,
    clientName: 'Godard Ors',
    date: '2/16/2023',
    status: false,
    amount: '$5.87',
    service: 'Push',
  },
  {
    transactionId: 12,
    clientName: 'Hersch Prugel',
    date: '7/29/2022',
    status: false,
    amount: '$5.26',
    service: 'Push',
  },
  {
    transactionId: 13,
    clientName: 'Dillon Lutwidge',
    date: '9/14/2022',
    status: true,
    amount: '$4.36',
    service: 'Push',
  },
  {
    transactionId: 14,
    clientName: 'Donal Howsin',
    date: '6/13/2023',
    status: false,
    amount: '$2.24',
    service: 'Push',
  },
  {
    transactionId: 15,
    clientName: 'Austen Peaple',
    date: '1/2/2023',
    status: true,
    amount: '$3.11',
    service: 'Push',
  },
];

export const userList = [
  {
    joinedDate: '11/1/2022',
    organizationName: 'Williamson Inc',
    smsBalance: 1319,
    activeForms: 1,
  },
  {
    joinedDate: '4/3/2023',
    organizationName: 'Reinger-Sipes',
    smsBalance: 1678,
    activeForms: 2,
  },
  {
    joinedDate: '6/14/2023',
    organizationName: 'Blanda LLC',
    smsBalance: 148,
    activeForms: 3,
  },
  {
    joinedDate: '6/16/2023',
    organizationName: 'Abernathy-Veum',
    smsBalance: 1483,
    activeForms: 4,
  },
  {
    joinedDate: '1/26/2023',
    organizationName: 'MacGyver Group',
    smsBalance: 205,
    activeForms: 5,
  },
  {
    joinedDate: '6/1/2023',
    organizationName: 'Sipes and Sons',
    smsBalance: 319,
    activeForms: 6,
  },
  {
    joinedDate: '2/15/2023',
    organizationName: 'Rice Group',
    smsBalance: 418,
    activeForms: 7,
  },
  {
    joinedDate: '2/28/2023',
    organizationName: 'Turcotte-Bins',
    smsBalance: 2026,
    activeForms: 8,
  },
  {
    joinedDate: '10/8/2022',
    organizationName: 'Miller, Robel and Ullrich',
    smsBalance: 1923,
    activeForms: 9,
  },
  {
    joinedDate: '10/20/2022',
    organizationName: 'Oberbrunner, Walter and Lynch',
    smsBalance: 1278,
    activeForms: 10,
  },
  {
    joinedDate: '8/19/2022',
    organizationName: 'Harris, Luettgen and Rutherford',
    smsBalance: 2152,
    activeForms: 11,
  },
  {
    joinedDate: '10/19/2022',
    organizationName: 'Paucek-Thiel',
    smsBalance: 1593,
    activeForms: 12,
  },
  {
    joinedDate: '8/3/2022',
    organizationName: 'Kemmer Group',
    smsBalance: 469,
    activeForms: 13,
  },
  {
    joinedDate: '3/22/2023',
    organizationName: 'Senger Inc',
    smsBalance: 1582,
    activeForms: 14,
  },
  {
    joinedDate: '12/7/2022',
    organizationName: 'Dietrich, Hermann and Braun',
    smsBalance: 1029,
    activeForms: 15,
  },
  {
    joinedDate: '6/22/2023',
    organizationName: 'Steuber, Greenfelder and Nitzsche',
    smsBalance: 1621,
    activeForms: 16,
  },
  {
    joinedDate: '10/12/2022',
    organizationName: 'Kilback-Connelly',
    smsBalance: 1334,
    activeForms: 17,
  },
  {
    joinedDate: '9/14/2022',
    organizationName: 'Champlin Group',
    smsBalance: 1392,
    activeForms: 18,
  },
  {
    joinedDate: '10/12/2022',
    organizationName: 'Breitenberg-Barton',
    smsBalance: 920,
    activeForms: 19,
  },
  {
    joinedDate: '11/5/2022',
    organizationName: 'Schamberger, Stokes and Lehner',
    smsBalance: 580,
    activeForms: 20,
  },
];

export const clientInsytData = [
  {
    dateCreated: '4/1/2023',
    campaignName: 'Jacobs and Sons',
    status: false,
    responses: 1,
  },
  {
    dateCreated: '5/20/2023',
    campaignName: 'Baumbach and Sons',
    status: false,
    responses: 2,
  },
  {
    dateCreated: '6/17/2023',
    campaignName: 'Hyatt and Sons',
    status: true,
    responses: 3,
  },
  {
    dateCreated: '1/6/2023',
    campaignName: 'Stamm, Stehr and Sipes',
    status: true,
    responses: 4,
  },
  {
    dateCreated: '10/2/2022',
    campaignName: 'Walker, Ortiz and Oberbrunner',
    status: true,
    responses: 5,
  },
  {
    dateCreated: '1/30/2023',
    campaignName: 'Schultz, Mann and Roberts',
    status: false,
    responses: 6,
  },
  {
    dateCreated: '2/25/2023',
    campaignName: 'Ferry, Ryan and Jacobi',
    status: false,
    responses: 7,
  },
  {
    dateCreated: '9/10/2022',
    campaignName: 'Schneider, Heathcote and Bartoletti',
    status: true,
    responses: 8,
  },
  {
    dateCreated: '5/29/2023',
    campaignName: 'Steuber and Sons',
    status: true,
    responses: 9,
  },
  {
    dateCreated: '8/21/2022',
    campaignName: 'Reinger Inc',
    status: false,
    responses: 10,
  },
  {
    dateCreated: '11/21/2022',
    campaignName: 'Heller, Orn and Ebert',
    status: false,
    responses: 11,
  },
  {
    dateCreated: '4/21/2023',
    campaignName: 'Ullrich LLC',
    status: false,
    responses: 12,
  },
  {
    dateCreated: '8/1/2022',
    campaignName: 'Muller, Kirlin and Rogahn',
    status: false,
    responses: 13,
  },
  {
    dateCreated: '5/26/2023',
    campaignName: 'Feil and Sons',
    status: true,
    responses: 14,
  },
  {
    dateCreated: '3/5/2023',
    campaignName: 'Lind and Sons',
    status: true,
    responses: 15,
  },
  {
    dateCreated: '10/22/2022',
    campaignName: 'Champlin-Conroy',
    status: false,
    responses: 16,
  },
  {
    dateCreated: '10/24/2022',
    campaignName: 'Flatley-Wuckert',
    status: true,
    responses: 17,
  },
  {
    dateCreated: '3/23/2023',
    campaignName: 'Langworth, Fahey and Schaefer',
    status: true,
    responses: 18,
  },
  {
    dateCreated: '12/24/2022',
    campaignName: 'Price, Marvin and Heidenreich',
    status: true,
    responses: 19,
  },
  {
    dateCreated: '2/12/2023',
    campaignName: 'Shanahan-Durgan',
    status: true,
    responses: 20,
  },
];
