export const recentPayments = [
  {
    transactionId: 1,
    clientName: 'Bink MacPhail',
    date: '2/14/2023',
    status: false,
    amount: '$3.49',
    service: 'Push',
  },
  {
    transactionId: 2,
    clientName: 'Bay Ridler',
    date: '12/6/2022',
    status: false,
    amount: '$6.44',
    service: 'Push',
  },
  {
    transactionId: 3,
    clientName: 'Scarlett Wyche',
    date: '10/31/2022',
    status: true,
    amount: '$6.75',
    service: 'Push',
  },
  {
    transactionId: 4,
    clientName: 'Birk Coolahan',
    date: '7/6/2023',
    status: true,
    amount: '$6.43',
    service: 'Push',
  },
  {
    transactionId: 5,
    clientName: 'Farra Coatts',
    date: '3/8/2023',
    status: false,
    amount: '$5.51',
    service: 'Push',
  },
  {
    transactionId: 6,
    clientName: 'Jobey Patemore',
    date: '9/9/2022',
    status: true,
    amount: '$7.69',
    service: 'Push',
  },
  {
    transactionId: 7,
    clientName: 'Stu Bullough',
    date: '1/3/2023',
    status: true,
    amount: '$5.43',
    service: 'Push',
  },
  {
    transactionId: 8,
    clientName: 'Krystle Cushelly',
    date: '7/28/2022',
    status: false,
    amount: '$0.14',
    service: 'Push',
  },
  {
    transactionId: 9,
    clientName: 'Laurent Ondrus',
    date: '10/9/2022',
    status: true,
    amount: '$1.12',
    service: 'Push',
  },
  {
    transactionId: 10,
    clientName: 'Jimmy Oyley',
    date: '12/20/2022',
    status: true,
    amount: '$4.58',
    service: 'Push',
  },
  {
    transactionId: 11,
    clientName: 'Godard Ors',
    date: '2/16/2023',
    status: false,
    amount: '$5.87',
    service: 'Push',
  },
  {
    transactionId: 12,
    clientName: 'Hersch Prugel',
    date: '7/29/2022',
    status: false,
    amount: '$5.26',
    service: 'Push',
  },
  {
    transactionId: 13,
    clientName: 'Dillon Lutwidge',
    date: '9/14/2022',
    status: true,
    amount: '$4.36',
    service: 'Push',
  },
  {
    transactionId: 14,
    clientName: 'Donal Howsin',
    date: '6/13/2023',
    status: false,
    amount: '$2.24',
    service: 'Push',
  },
  {
    transactionId: 15,
    clientName: 'Austen Peaple',
    date: '1/2/2023',
    status: true,
    amount: '$3.11',
    service: 'Push',
  },
];
