import { useForm } from 'react-hook-form';
import { useState } from 'react';
import { useDepartments } from '../hooks/fetchers';
import api from '../utils/axiosInstance';

const generatePassword = length => {
  const charset =
    'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()-_=+';
  let password = '';
  for (let i = 0; i < length; i++) {
    const randomIndex = Math.floor(Math.random() * charset.length);
    password += charset.charAt(randomIndex);
  }

  return password;
};

const AdminModal = ({ modalState, close }) => {
  const [autoGeneratedPassword, setAutoGeneratedPassword] = useState('');
  const [selectedDepartment, setSelectedDepartment] = useState('');
  const [isChecked, setIsChecked] = useState(false);
  const { departments } = useDepartments();
  const defaultValues = {
    name: '',
    role: '',
    department: '',
    password: '',
    email: '',
  };

  const {
    handleSubmit,
    register,
    reset,
    clearErrors,
    formState: { errors },
  } = useForm(defaultValues);

  console.log(selectedDepartment);

  const handleCheckBoxChange = () => {
    setIsChecked(prev => !prev);
  };
  return (
    <div>
      {modalState && (
        <div className='fixed top-0 bottom-0 left-0 right-0 z-50 flex items-center justify-center backdrop-blur-[2px] backdrop-invert-[20%] font-sans  '>
          <div className='lg:w-[50%] 2xl:w-[40%] p-4 mx-auto bg-white rounded-lg shadow-lg'>
            <h2 className='mb-4 text-xl font-bold'>Add New Admin</h2>
            <form
              onSubmit={handleSubmit(data => {
                api
                  .post('/admins/add-admin', {
                    ['name']: data.name,
                    roleCode: data.role,
                    department: data.department,
                    password: data.password,
                    email: data.email,
                  })
                  .then(() => {
                    alert('Admin added');
                    clearErrors();
                    reset();
                  })
                  .catch(() => alert('Failed to add Admin'));
              })}
            >
              <div className='flex flex-col w-full gap-5 py-4'>
                <div className='flex flex-col w-full gap-2'>
                  <p>Name:</p>
                  <input
                    type='text'
                    className='border-[1px] py-3 px-5 rounded'
                    placeholder='John Doe'
                    {...register('name', { required: 'Enter user name' })}
                  />
                </div>
                <div className='flex flex-col w-full gap-2'>
                  <p>Email:</p>
                  <input
                    type='text'
                    className='border-[1px] py-3 px-5 rounded'
                    placeholder='john@email.com'
                    {...register('email', { required: 'Enter email' })}
                  />
                </div>
                <div className='flex flex-col w-full gap-2'>
                  <p>Department:</p>
                  <select
                    type='text'
                    className='border-[1px] bg-white py-3 px-5 rounded focus:outline-none'
                    placeholder='Department'
                    {...register('department', {
                      required: 'Enter department',
                      onChange: event =>
                        setSelectedDepartment(event.target.value),
                    })}
                  >
                    <option value=''>Select a department</option>
                    {departments?.map(department => (
                      <option value={department.name}>{department.name}</option>
                    ))}
                  </select>
                </div>
                <div className='flex flex-col w-full gap-2'>
                  <p>Role:</p>
                  <select
                    type='text'
                    className='border-[1px] bg-white py-3 px-5 rounded focus:outline-none'
                    placeholder='Role'
                    {...register('role', { required: 'Enter role' })}
                  >
                    <option value=''>Select a role</option>
                    {departments
                      .find(
                        department => department.name === selectedDepartment
                      )
                      ?.roles.map(role => (
                        <option key={role.code} value={role.code}>
                          {role.name}
                        </option>
                      ))}
                  </select>
                </div>
                <div className='flex flex-col w-full gap-2'>
                  <p>Password:</p>
                  <div className='flex flex-col w-full gap-2'>
                    <input
                      type='text'
                      className='border-[1px] bg-white py-3 px-5 rounded focus:outline-none'
                      placeholder='password'
                      {...register('password')}
                    />
                    <div className='flex flex-row items-center gap-2'>
                      <input
                        type='checkbox'
                        name=''
                        id=''
                        className=''
                        onChange={handleCheckBoxChange}
                        checked={isChecked}
                      />
                      <p className='text-sm'>Auto Generate Password</p>
                    </div>
                  </div>
                </div>
              </div>
              <div className='flex justify-end'>
                <button
                  type='button'
                  onClick={close}
                  className='px-4 py-2 mr-2 font-bold text-white bg-gray-500 rounded hover:bg-gray-700'
                >
                  Cancel
                </button>
                <button
                  type='submit'
                  className='px-4 py-2 font-bold text-white bg-[#0FA958] rounded hover:scale-110'
                >
                  Add Admin
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

export default AdminModal;
